# Generated by Django 5.0.6 on 2024-05-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
