# Generated by Django 5.0.6 on 2024-05-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='imag',
        ),
        migrations.RemoveField(
            model_name='application',
            name='image',
        ),
        migrations.RemoveField(
            model_name='currencynews',
            name='image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='onemoment',
            name='image',
        ),
    ]
