# Generated by Django 5.0.6 on 2024-05-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getapps', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='language',
        ),
    ]
