# Generated by Django 5.0.6 on 2024-05-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getapps', '0004_remove_discount_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='currencynews',
            options={},
        ),
    ]
