# Generated by Django 5.0.6 on 2024-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getapps', '0005_alter_contest_options_alter_currencynews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='footer_images/', verbose_name='Image'),
        ),
    ]
