# Generated by Django 5.0.6 on 2024-05-24 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getapps', '0006_footer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'verbose_name': 'Конкурс', 'verbose_name_plural': 'Конкурсы'},
        ),
    ]
