# Generated by Django 5.0.6 on 2024-05-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getapps', '0007_alter_contest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencynews',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
